package com.solarwizard.service;

import java.util.Map;

/**
 * Centralized contextual help text for the wizard screens.
 * Written in plain language for non-technical users.
 */
public final class GuideService {

    private static final String FALLBACK_GUIDE = String.join("\n",
        "Not sure what to do here? No worries!",
        "",
        "Just follow these simple tips:",
        "1. Fill in the boxes from top to bottom.",
        "2. If you see a warning, try to fix it before going to the next step.",
        "3. You can save your work anytime using the Save Draft button on the left.",
        "4. Come back to any step at any time using the menu on the left side."
    );

    private static final Map<String, String> GUIDES = Map.ofEntries(

        // ── 1. Main Menu ─────────────────────────────────────────────────────────
        Map.entry("Main Menu", String.join("\n",
            "Welcome to Solar Sizing Wizard!",
            "",
            "This is your home screen. Here is what you can do:",
            "",
            "Starting a new project:",
            "1. Click the big blue \"Start Drafting Now\" button to begin.",
            "2. The app will walk you through each step one at a time.",
            "",
            "Opening a project you already started:",
            "1. Look for your project name under \"Past Computed Projects\".",
            "2. Click \"Open\" next to it to pick up where you left off.",
            "3. If you got a project file from someone else, click \"Import\" to load it.",
            "",
            "Choosing where to save your files:",
            "- Click \"Change Directory\" to pick a folder on your computer",
            "  where your projects will be saved.",
            "",
            "Tip:",
            "If your project is not showing up in the list, click \"Change Directory\"",
            "and point it to the folder where you saved the file."
        )),

        // ── 2. Appliances ────────────────────────────────────────────────────────
        Map.entry("Appliances", String.join("\n",
            "Step 1 of 8 - What appliances do you use at home?",
            "",
            "In this step, you will list all the devices and appliances",
            "you want the solar system to power.",
            "",
            "How to add an appliance:",
            "1. Click \"+ Add Device\", or tap one of the shortcut buttons",
            "   like Air Conditioner, Refrigerator, or LED TV.",
            "2. Fill in the details for each appliance:",
            "   - Watts: How much power it uses. Check the label at the back",
            "     of the appliance or look it up in its manual.",
            "   - Hrs/Day: How many hours a day you normally use it.",
            "   - Peak Hr: How many hours you use it at its busiest time of day.",
            "   - Qty: How many of this appliance you have at home.",
            "   - Motor?: Tick this box if the appliance has a motor inside",
            "     (like a ref, washing machine, or air conditioner).",
            "     This helps the app account for the extra power it needs to start up.",
            "3. Repeat for each appliance you want to include.",
            "4. When done, click \"Next\" to continue.",
            "",
            
            "Tip:",
            "The more accurate your hours per day, the better your system size will be.",
            "When in doubt, round up slightly to be safe."
        )),

        // ── 3. Energy Requirement ────────────────────────────────────────────────
        Map.entry("Energy Requirement", String.join("\n",
            "Step 2 of 8 - How much energy do you need?",
            "",
            "This step calculates the total energy your solar system needs to produce.",
            "You just need to answer two simple questions:",
            "",
            "1. System Loss Buffer:",
            "   Solar systems are not 100% perfect. Some energy is always lost",
            "   due to heat, wiring, and the inverter. This setting adds extra",
            "   capacity to make up for that.",
            "   - The recommended starting value is 30%.",
            "   - You can leave it at 30% if you are unsure.",
            "",
            "2. Days of Autonomy:",
            "   How many days do you want your batteries to keep the lights on",
            "   even if there is no sun? (Think rainy or cloudy days.)",
            "   - Enter at least 1 to 2 days as a starting point.",
            "   - More days means more battery storage will be needed.",
            "",
            "Once you fill these in, click \"Next\" and the app will",
            "figure out the rest for the next steps."
        )),

        // ── 4. Battery Bank ──────────────────────────────────────────────────────
        Map.entry("Battery Bank", String.join("\n",
            "Step 3 of 8 - Choose your batteries.",
            "",
            "Batteries store the energy your solar panels collect during the day",
            "so you can use it at night or on cloudy days.",
            "",
            "Here is how to fill in this step:",
            "",
            "1. Enter the Brand and Model of the battery you plan to buy.",
            "   (This is just for your records.)",
            "",
            "2. Nominal Voltage: Pick the voltage printed on your battery.",
            "   Common options are 12V, 24V, 48V.",
            "",
            "3. Capacity (Ah): Enter the Ah number from the battery label.",
            "   Ah (ampere-hour) tells you how much energy the battery can hold.",
            "",
            "4. Depth of Discharge (DOD): This is how much of the battery",
            "   you are allowed to use before it needs recharging.",
            "   - If you have a regular Lead-Acid battery, enter 0.50 (that is 50%).",
            "   - If you have a LiFePO4 (lithium) battery, enter 0.80 (that is 80%).",
            "   - Not sure what type you have? Check the battery label or manual.",
            "",
            "5. Battery Quantity: Increase the number of batteries until",
            "   the Required Capacity number is satisfied.",
            "   The app will tell you when you have enough.",
            "",
            "Once you are happy with the numbers, click \"Next\" to continue."
        )),

        // ── 5. Panel Array ───────────────────────────────────────────────────────
        Map.entry("Panel Array", String.join("\n",
            "Step 4 of 8 - Choose your solar panels.",
            "",
            "In this step, you enter the details of the solar panels you plan to use.",
            "You can find all of these numbers on the panel's datasheet or product label.",
            "",
            "Here is what to fill in:",
            "",
            "1. Brand and Model: The name of the panel (for your records).",
            "",
            "2. Wattage (W): The power output of one panel.",
            "   Usually printed as something like \"400W\" on the panel.",
            "",
            "3. Voc, Vmp, Isc, Imp, Efficiency:",
            "   These are electrical values from the panel datasheet.",
            "   Just copy the numbers directly from the spec sheet.",
            "   - Voc and Vmp are voltage values.",
            "   - Isc and Imp are current values.",
            "   - Efficiency is a percentage (e.g. 20%).",
            "",
            "4. Peak Sun Hours (PSH): The average number of hours per day",
            "   your location gets strong sunlight.",
            "   - In the Philippines, a common estimate is around 4 to 5 hours.",
            "   - Use a slightly lower number to be on the safe side.",
            "",
            "5. Wiring Configuration: Choose how your panels are connected.",
            "   - If unsure, go with the option your installer recommends.",
            "",
            "The app will then calculate how many panels you need.",
            "Click \"Next\" when you are ready."
        )),

        // ── 6. Charge Controller ─────────────────────────────────────────────────
        Map.entry("Charge Controller", String.join("\n",
            "Step 5 of 8 - Choose your charge controller.",
            "",
            "A charge controller is the device that sits between your solar panels",
            "and your batteries. It controls how the panels charge the batteries",
            "and protects everything from overcharging.",
            "",
            "Here is what to fill in:",
            "",
            "1. Controller Type:",
            "   - Choose MPPT if you are unsure. It is more efficient and works",
            "     well for most off-grid home setups.",
            "   - PWM is an older and simpler type.",
            "",
            "2. Rated Charge Current (A), Max PV Input Voltage (V),",
            "   and Max PV Input Power (W):",
            "   - These three numbers are on the charge controller's box or manual.",
            "   - Just copy them in.",
            "",
            "Important:",
            "The app will check if the controller you chose is strong enough",
            "to handle your panels. If it shows a warning, you may need a",
            "bigger or different controller.",
            "",
            "Click \"Next\" once the app shows no warnings."
        )),

        // ── 7. Inverter Sizing ───────────────────────────────────────────────────
        Map.entry("Inverter Sizing", String.join("\n",
            "Step 6 of 8 - Choose your inverter.",
            "",
            "An inverter converts the battery's stored energy into the regular",
            "AC electricity that your appliances use at home.",
            "",
            "Here is what to fill in:",
            "",
            "1. Brand and Model: The inverter you plan to buy (for your records).",
            "",
            "2. Rated Power (W): The maximum continuous output of the inverter.",
            "   This is printed on the box, usually something like \"3000W\" or \"5000W\".",
            "",
            "Important:",
            "The app will check if the inverter is big enough for your appliances.",
            "- Make sure the Rated Power is higher than the minimum shown by the app.",
            "- If you have appliances with motors (ref, aircon, washing machine),",
            "  you may need an inverter rated higher to handle the startup surge.",
            "",
            "Click \"Next\" once you have entered your inverter details."
        )),

        // ── 8. Wire Sizing ───────────────────────────────────────────────────────
        Map.entry("Wire Sizing", String.join("\n",
            "Step 7 of 8 - How far apart is everything?",
            "",
            "This step helps the app figure out what wire thickness to recommend",
            "for each section of your solar setup.",
            "Thicker wires are needed for longer runs to avoid energy loss.",
            "",
            "Here is what to fill in:",
            "",
            "1. Enter the cable distance (in meters) for each section:",
            "   - Panels to Charge Controller: How far are your panels from the controller?",
            "   - Charge Controller to Battery: How far is the controller from the batteries?",
            "   - Inverter to AC Load (Panel Board): How far is the inverter from",
            "     your home's electrical panel or outlets?",
            "",
            "2. DC Voltage Drop (%): Leave this at 2% if you are unsure.",
            "   This is the standard safe value used by most installers.",
            "",
            "The app will then show you a table with the recommended wire sizes.",
            "Just hand this information to your installer.",
            "",
            "Tip:",
            "Try to keep your charge controller and batteries close together.",
            "Shorter wires in this section means less energy loss."
        )),

        // ── 9. Circuit Breakers ──────────────────────────────────────────────────
        Map.entry("Circuit Breakers", String.join("\n",
            "Step 8 of 8 - Review your protection devices.",
            "",
            "Circuit breakers (also called MCBs) protect your solar system's wiring",
            "from overheating and short circuits. This step shows you what ratings",
            "to look for when buying them.",
            "",
            "What this step does:",
            "The app automatically calculates the breaker sizes needed",
            "for each section based on your earlier inputs.",
            "You do not need to enter anything here - just review the results.",
            "",
            "What to look at:",
            "- Each row shows a section of your system and the breaker size needed.",
            "- The app also shows recommendations for extra safety devices like:",
            "  - Surge Protection Devices (SPD): Protects against lightning and",
            "    sudden voltage spikes.",
            "  - Automatic Transfer Switches (ATS): Automatically switches between",
            "    solar and grid/generator power.",
            "  - DC Isolators: Acts as a safety switch for the solar panel side.",
            "",
            "Important note:",
            "Share these results with your licensed electrician or installer.",
            "They will make the final decision based on local electrical rules.",
            "",
            "When you are done reviewing, click \"View Report\" to see your",
            "complete solar system summary."
        )),

        // ── 10. Summary Report ───────────────────────────────────────────────────
        Map.entry("Summary Report", String.join("\n",
            "You're done! Here is your Solar System Summary.",
            "",
            "This page shows the complete result of all your inputs and calculations.",
            "You can use this as a reference when buying equipment or talking to an installer.",
            "",
            "What to check before you save:",
            "",
            "1. Look at the banner at the top of the page.",
            "   - If it says \"All checks passed\", you are good to go!",
            "   - If it shows a warning, go back to that step and adjust your inputs.",
            "",
            "2. Review your recommended equipment:",
            "   - Battery bank size and type.",
            "   - Number and type of solar panels.",
            "   - Charge controller rating.",
            "   - Inverter rating.",
            "   - Wire sizes and circuit breaker ratings.",
            "",
            "Saving your design:",
            "- Click \"Save Draft\" on the left sidebar to save your final design.",
            "  You can open it again any time from the Home Screen.",
            "",
            "Tip:",
            "If something looks off, click on any step in the left sidebar to go back",
            "and change your inputs. Your summary will update automatically."
        ))
    );

    private GuideService() {}

    public static String guideFor(String stepTitle) {
        return GUIDES.getOrDefault(stepTitle, FALLBACK_GUIDE);
    }
}
