package com.solarwizard.service;

import java.util.Map;

/**
 * Centralized contextual help text for the wizard screens.
 * Written in plain language for non-technical users.
 */
public final class GuideService {

    private static final String FALLBACK_GUIDE = String.join("\n",
        "Not sure what to do here? No worries!",
        "",
        "Just follow these simple tips:",
        "1. Fill in the boxes from top to bottom.",
        "2. If you see a warning, try to fix it before going to the next step.",
        "3. You can save your work anytime using the Save Draft button on the left.",
        "4. Come back to any step at any time using the menu on the left side."
    );

    private static final Map<String, String> GUIDES = Map.ofEntries(

        // ── 1. Main Menu ─────────────────────────────────────────────────────────
        Map.entry("Main Menu", String.join("\n",
            "Welcome to Solar Sizing Wizard!",
            "",
            "This is your home screen. Here is what you can do:",
            "",
            "Starting a new project:",
            "1. Click the big blue \"Start Drafting Now\" button to begin.",
            "2. The app will walk you through each step one at a time.",
            "",
            "Opening a project you already started:",
            "1. Look for your project name under \"Past Computed Projects\".",
            "2. Click \"Open\" next to it to pick up where you left off.",
            "3. If you got a project file from someone else, click \"Import\" to load it.",
            "",
            "Choosing where to save your files:",
            "- Click \"Change Directory\" to pick a folder on your computer",
            "  where your projects will be saved.",
            "",
            "Tip:",
            "If your project is not showing up in the list, click \"Change Directory\"",
            "and point it to the folder where you saved the file."
        )),

        // ── 2. Appliances ────────────────────────────────────────────────────────
        Map.entry("Appliances", String.join("\n",
            "Step 1 of 8 - What appliances do you use at home?",
            "",
            "What is a load list?",
            "Before a solar system can be designed, we first need to know",
            "how much electricity your home actually uses. Every device that",
            "runs on electricity - from your refrigerator to your phone charger -",
            "draws a certain amount of power measured in watts (W). When you",
            "add up all those devices and how long you use each one per day,",
            "you get your total daily energy load, measured in watt-hours (Wh).",
            "This number is the foundation for everything else: it determines",
            "how big your battery bank needs to be, how many solar panels you",
            "need, and what size inverter and charge controller to use.",
            "The more complete and accurate your list is here, the better",
            "the rest of the design will be.",
            "",
            "In this step, you will list all the devices and appliances",
            "you want the solar system to power.",
            "",
            "How to add an appliance:",
            "1. Click \"+ Add Device\", or tap one of the shortcut buttons",
            "   like Air Conditioner, Refrigerator, or LED TV.",
            "2. Fill in the details for each appliance:",
            "   - Watts: How much power it uses. Check the label at the back",
            "     of the appliance or look it up in its manual.",
            "   - Hrs/Day: How many hours a day you normally use it.",
            "   - Peak Hr: How many hours you use it at its busiest time of day.",
            "   - Qty: How many of this appliance you have at home.",
            "   - Motor?: Tick this box if the appliance has a motor inside",
            "     (like a ref, washing machine, or air conditioner).",
            "     This helps the app account for the extra power it needs to start up.",
            "3. Repeat for each appliance you want to include.",
            "4. When done, click \"Next\" to continue.",
            "",
            
            "Tip:",
            "The more accurate your hours per day, the better your system size will be.",
            "When in doubt, round up slightly to be safe."
        )),

        // ── 3. Energy Requirement ────────────────────────────────────────────────
        Map.entry("Energy Requirement", String.join("\n",
            "Step 2 of 8 - How much energy do you need?",
            "",
            "What is energy requirement?",
            "In the previous step, you listed your appliances. This step takes",
            "that raw list and turns it into a design target - a specific number",
            "the rest of the system must be able to deliver.",
            "",
            "Real-world solar systems are never 100% efficient. Energy is lost",
            "as heat in wires, as heat inside the inverter, and during the process",
            "of charging and discharging batteries. If you design a system that",
            "only barely meets your appliance load, those losses will leave you",
            "short. The System Loss Buffer adds a safety margin on top to cover",
            "these invisible losses.",
            "",
            "Days of Autonomy addresses a different problem: the sun does not",
            "shine every day. Typhoons, heavy rain, and thick cloud cover can",
            "cut solar production to near zero for one or more days at a time.",
            "Autonomy days tell the app how many of those sunless days your",
            "battery bank should be able to carry you through without recharging.",
            "More autonomy days means a larger battery bank.",
            "",
            "This step calculates the total energy your solar system needs to produce.",
            "You just need to answer two simple questions:",
            "",
            "1. System Loss Buffer:",
            "   Solar systems are not 100% perfect. Some energy is always lost",
            "   due to heat, wiring, and the inverter. This setting adds extra",
            "   capacity to make up for that.",
            "   - The recommended starting value is 30%.",
            "   - You can leave it at 30% if you are unsure.",
            "",
            "2. Days of Autonomy:",
            "   How many days do you want your batteries to keep the lights on",
            "   even if there is no sun? (Think rainy or cloudy days.)",
            "   - Enter at least 1 to 2 days as a starting point.",
            "   - More days means more battery storage will be needed.",
            "",
            "Once you fill these in, click \"Next\" and the app will",
            "figure out the rest for the next steps."
        )),

        // ── 4. Battery Bank ──────────────────────────────────────────────────────
        Map.entry("Battery Bank", String.join("\n",
            "Step 3 of 8 - Choose your batteries.",
            "",
            "What is a battery bank?",
            "A single battery may not be large enough to store all the energy",
            "your home needs. A battery bank is simply a group of batteries",
            "connected together to act as one large storage unit.",
            "",
            "Think of it like water tanks: one small tank might not hold enough",
            "water for your family for two days, but four tanks connected",
            "together can. The same idea applies here.",
            "",
            "Batteries are rated in ampere-hours (Ah), which tells you the",
            "total charge they can hold. But you cannot safely use 100% of that",
            "charge - doing so shortens the battery's life significantly.",
            "The Depth of Discharge (DOD) setting is how the app accounts",
            "for this limit. A 50% DOD on a 200Ah battery, for example, means",
            "you only plan to use 100Ah before recharging.",
            "",
            "Different battery chemistries have different safe discharge limits:",
            "Lead-acid batteries (the common, heavier type) should not go below",
            "50%, while modern LiFePO4 lithium batteries can safely go down",
            "to 20% remaining (80% DOD) without damage.",
            "",
            "Batteries store the energy your solar panels collect during the day",
            "so you can use it at night or on cloudy days.",
            "",
            "Here is how to fill in this step:",
            "",
            "1. Enter the Brand and Model of the battery you plan to buy.",
            "   (This is just for your records.)",
            "",
            "2. Nominal Voltage: Pick the voltage printed on your battery.",
            "   Common options are 12V, 24V, 48V.",
            "",
            "3. Capacity (Ah): Enter the Ah number from the battery label.",
            "   Ah (ampere-hour) tells you how much energy the battery can hold.",
            "",
            "4. Depth of Discharge (DOD): This is how much of the battery",
            "   you are allowed to use before it needs recharging.",
            "   - If you have a regular Lead-Acid battery, enter 0.50 (that is 50%).",
            "   - If you have a LiFePO4 (lithium) battery, enter 0.80 (that is 80%).",
            "   - Not sure what type you have? Check the battery label or manual.",
            "",
            "5. Battery Quantity: Increase the number of batteries until",
            "   the Required Capacity number is satisfied.",
            "   The app will tell you when you have enough.",
            "",
            "Once you are happy with the numbers, click \"Next\" to continue."
        )),

        // ── 5. Panel Array ───────────────────────────────────────────────────────
        Map.entry("Panel Array", String.join("\n",
            "Step 4 of 8 - Choose your solar panels.",
            "",
            "What is a solar panel?",
            "A solar panel is a flat device made up of many small solar cells.",
            "Each cell is made from a special material (usually silicon) that",
            "produces a small electric current when sunlight hits it.",
            "Many cells are wired together inside one panel to produce a",
            "useful amount of electricity - typically between 100W and 600W",
            "for a single residential panel.",
            "",
            "What is a panel array?",
            "Just like batteries are grouped into a battery bank, solar panels",
            "are grouped into an array. A panel array is simply two or more",
            "solar panels connected together to produce more power than a",
            "single panel can on its own.",
            "",
            "Panels in an array can be wired in two ways:",
            "- Series: panels are chained end-to-end, which increases the",
            "  voltage while keeping the current the same.",
            "- Parallel: panels are connected side by side, which increases",
            "  the current while keeping the voltage the same.",
            "- Series-Parallel: a combination of both, used to match the",
            "  exact voltage and current your charge controller expects.",
            "",
            "The size of your array (how many panels you need) depends on",
            "how much energy your home uses and how many hours of good",
            "sunlight your location receives per day.",
            "",
            "In this step, you enter the details of the solar panels you plan to use.",
            "You can find all of these numbers on the panel's datasheet or product label.",
            "",
            "Here is what to fill in:",
            "",
            "1. Brand and Model: The name of the panel (for your records).",
            "",
            "2. Wattage (W): The power output of one panel.",
            "   Usually printed as something like \"400W\" on the panel.",
            "",
            "3. Voc, Vmp, Isc, Imp, Efficiency:",
            "   These are electrical values from the panel datasheet.",
            "   Just copy the numbers directly from the spec sheet.",
            "   - Voc and Vmp are voltage values.",
            "   - Isc and Imp are current values.",
            "   - Efficiency is a percentage (e.g. 20%).",
            "",
            "4. Peak Sun Hours (PSH): The average number of hours per day",
            "   your location gets strong sunlight.",
            "   - In the Philippines, a common estimate is around 4 to 5 hours.",
            "   - Use a slightly lower number to be on the safe side.",
            "",
            "5. Wiring Configuration: Choose how your panels are connected.",
            "   - If unsure, go with the option your installer recommends.",
            "",
            "The app will then calculate how many panels you need.",
            "Click \"Next\" when you are ready."
        )),

        // ── 6. Charge Controller ─────────────────────────────────────────────────
        Map.entry("Charge Controller", String.join("\n",
            "Step 5 of 8 - Choose your charge controller.",
            "",
            "What is a charge controller?",
            "A charge controller is the device that sits between your solar panels",
            "and your batteries. It controls how the panels charge the batteries",
            "and protects everything from overcharging.",
            "",
            "Without a charge controller, the voltage coming from the solar panels",
            "would be fed directly into the batteries. This would overcharge them,",
            "cause them to overheat, and permanently damage them in a short time.",
            "The charge controller constantly monitors the battery voltage and",
            "automatically reduces or stops the charging current once the batteries",
            "are full.",
            "",
            "There are two main types:",
            "",
            "PWM (Pulse Width Modulation):",
            "An older, simpler technology. It works by rapidly switching the",
            "connection between the panels and batteries on and off to regulate",
            "the voltage. It is inexpensive but less efficient, because it",
            "forces the panel to operate at the battery voltage rather than",
            "the panel's ideal voltage.",
            "",
            "MPPT (Maximum Power Point Tracking):",
            "A smarter, more modern type. It continuously adjusts to keep the",
            "solar panels operating at their most efficient voltage level,",
            "then converts that power to the voltage the batteries need.",
            "MPPT controllers typically recover 20-30% more energy from the",
            "same set of panels compared to PWM. For most home off-grid setups,",
            "MPPT is the recommended choice.",
            "",
            "Here is what to fill in:",
            "",
            "1. Controller Type:",
            "   - Choose MPPT if you are unsure. It is more efficient and works",
            "     well for most off-grid home setups.",
            "   - PWM is an older and simpler type.",
            "",
            "2. Rated Charge Current (A), Max PV Input Voltage (V),",
            "   and Max PV Input Power (W):",
            "   - These three numbers are on the charge controller's box or manual.",
            "   - Just copy them in.",
            "",
            "Important:",
            "The app will check if the controller you chose is strong enough",
            "to handle your panels. If it shows a warning, you may need a",
            "bigger or different controller.",
            "",
            "Click \"Next\" once the app shows no warnings."
        )),

        // ── 7. Inverter Sizing ───────────────────────────────────────────────────
        Map.entry("Inverter Sizing", String.join("\n",
            "Step 6 of 8 - Choose your inverter.",
            "",
            "What is an inverter?",
            "Your solar panels produce DC (direct current) electricity, and your",
            "batteries also store DC electricity. But the appliances in your home",
            "- lights, fans, televisions, refrigerators - run on AC (alternating",
            "current), the same type of electricity that comes from the grid.",
            "",
            "An inverter is the device that converts DC electricity from your",
            "batteries into AC electricity that your appliances can use.",
            "Without an inverter, you would not be able to run any standard",
            "household appliance from your solar system.",
            "",
            "Inverters are rated by the maximum continuous power they can",
            "deliver, measured in watts (W). If your home needs 2,000W running",
            "at the same time, your inverter must be rated at least 2,000W.",
            "",
            "Motor loads and surge power:",
            "Appliances with motors - air conditioners, refrigerators, washing",
            "machines, water pumps - need a large burst of extra power for just",
            "a second or two when they first start up. This is called the startup",
            "surge or inrush current. It can be 3 to 7 times the normal running",
            "watts. A properly sized inverter must be able to handle this surge",
            "without shutting down.",
            "",
            "An inverter converts the battery's stored energy into the regular",
            "AC electricity that your appliances use at home.",
            "",
            "Here is what to fill in:",
            "",
            "1. Brand and Model: The inverter you plan to buy (for your records).",
            "",
            "2. Rated Power (W): The maximum continuous output of the inverter.",
            "   This is printed on the box, usually something like \"3000W\" or \"5000W\".",
            "",
            "Important:",
            "The app will check if the inverter is big enough for your appliances.",
            "- Make sure the Rated Power is higher than the minimum shown by the app.",
            "- If you have appliances with motors (ref, aircon, washing machine),",
            "  you may need an inverter rated higher to handle the startup surge.",
            "",
            "Click \"Next\" once you have entered your inverter details."
        )),

        // ── 8. Wire Sizing ───────────────────────────────────────────────────────
        Map.entry("Wire Sizing", String.join("\n",
            "Step 7 of 8 - How far apart is everything?",
            "",
            "Why does wire size matter?",
            "Every wire has a small amount of resistance - it resists the flow",
            "of electricity, similar to how a narrow garden hose resists water",
            "flow. This resistance causes two problems: it wastes energy as",
            "heat, and it reduces the voltage reaching your equipment.",
            "",
            "The longer a wire run is, the more resistance it has, and the more",
            "voltage you lose along the way. This is called voltage drop.",
            "Too much voltage drop means your batteries may not charge fully,",
            "and your inverter may not perform well.",
            "",
            "The solution is to use thicker wire for longer runs. A thicker",
            "wire has less resistance per meter, so the voltage drop stays",
            "within acceptable limits. Wire thickness is measured in mm²",
            "(square millimeters) in the Philippines and most of Asia.",
            "",
            "Your solar system has three main cable sections that must each",
            "be sized correctly:",
            "- Panel array to charge controller (high-voltage DC section)",
            "- Charge controller to battery bank (lower-voltage DC section)",
            "- Inverter to your home's electrical panel (AC section)",
            "",
            "This step helps the app figure out what wire thickness to recommend",
            "for each section of your solar setup.",
            "Thicker wires are needed for longer runs to avoid energy loss.",
            "",
            "Here is what to fill in:",
            "",
            "1. Enter the cable distance (in meters) for each section:",
            "   - Panels to Charge Controller: How far are your panels from the controller?",
            "   - Charge Controller to Battery: How far is the controller from the batteries?",
            "   - Inverter to AC Load (Panel Board): How far is the inverter from",
            "     your home's electrical panel or outlets?",
            "",
            "2. DC Voltage Drop (%): Leave this at 2% if you are unsure.",
            "   This is the standard safe value used by most installers.",
            "",
            "The app will then show you a table with the recommended wire sizes.",
            "Just hand this information to your installer.",
            "",
            "Tip:",
            "Try to keep your charge controller and batteries close together.",
            "Shorter wires in this section means less energy loss."
        )),

        // ── 9. Circuit Breakers ──────────────────────────────────────────────────
        Map.entry("Circuit Breakers", String.join("\n",
            "Step 8 of 8 - Review your protection devices.",
            "",
            "What is a circuit breaker?",
            "A circuit breaker is a safety switch that automatically trips",
            "(switches off) when too much current flows through a wire.",
            "It protects your wiring from overheating - which can cause fires -",
            "and protects your equipment from damage caused by short circuits.",
            "",
            "Think of it as a fuse that you can reset instead of replace.",
            "In a solar system, circuit breakers are placed at key points to",
            "protect each section of cable independently.",
            "",
            "What about the other protection devices shown here?",
            "",
            "Surge Protection Device (SPD):",
            "A lightning strike near your home can send a sudden, massive",
            "voltage spike through your system in a fraction of a second.",
            "An SPD absorbs that spike and diverts it safely to the ground,",
            "protecting your panels, charge controller, and inverter.",
            "This is especially important in the Philippines due to the",
            "frequency of thunderstorms during the rainy season.",
            "",
            "Automatic Transfer Switch (ATS):",
            "An ATS automatically detects when your solar system runs low",
            "and switches your home over to the grid or a generator for",
            "backup power - then switches back to solar when it recovers.",
            "This happens in milliseconds, so you may not even notice.",
            "",
            "DC Isolator:",
            "A DC isolator is a manual safety switch on the solar panel side",
            "of the system. It lets you quickly and safely cut the power from",
            "the panels to the charge controller whenever maintenance is needed,",
            "without touching the panels themselves.",
            "",
            "Circuit breakers (also called MCBs) protect your solar system's wiring",
            "from overheating and short circuits. This step shows you what ratings",
            "to look for when buying them.",
            "",
            "What this step does:",
            "The app automatically calculates the breaker sizes needed",
            "for each section based on your earlier inputs.",
            "You do not need to enter anything here - just review the results.",
            "",
            "What to look at:",
            "- Each row shows a section of your system and the breaker size needed.",
            "- The app also shows recommendations for extra safety devices like:",
            "  - Surge Protection Devices (SPD): Protects against lightning and",
            "    sudden voltage spikes.",
            "  - Automatic Transfer Switches (ATS): Automatically switches between",
            "    solar and grid/generator power.",
            "  - DC Isolators: Acts as a safety switch for the solar panel side.",
            "",
            "Important note:",
            "Share these results with your licensed electrician or installer.",
            "They will make the final decision based on local electrical rules.",
            "",
            "When you are done reviewing, click \"View Report\" to see your",
            "complete solar system summary."
        )),

        // ── 10. Summary Report ───────────────────────────────────────────────────
        Map.entry("Summary Report", String.join("\n",
            "You're done! Here is your Solar System Summary.",
            "",
            "This page shows the complete result of all your inputs and calculations.",
            "You can use this as a reference when buying equipment or talking to an installer.",
            "",
            "What to check before you save:",
            "",
            "1. Look at the banner at the top of the page.",
            "   - If it says \"All checks passed\", you are good to go!",
            "   - If it shows a warning, go back to that step and adjust your inputs.",
            "",
            "2. Review your recommended equipment:",
            "   - Battery bank size and type.",
            "   - Number and type of solar panels.",
            "   - Charge controller rating.",
            "   - Inverter rating.",
            "   - Wire sizes and circuit breaker ratings.",
            "",
            "Saving your design:",
            "- Click \"Save Draft\" on the left sidebar to save your final design.",
            "  You can open it again any time from the Home Screen.",
            "",
            "Tip:",
            "If something looks off, click on any step in the left sidebar to go back",
            "and change your inputs. Your summary will update automatically."
        ))
    );

    private GuideService() {}

    public static String guideFor(String stepTitle) {
        return GUIDES.getOrDefault(stepTitle, FALLBACK_GUIDE);
    }
}
