package com.solarwizard.service;

import java.util.Map;

/**
 * Centralized contextual help text for the wizard screens.
 */
public final class GuideService {

    private static final String FALLBACK_GUIDE = String.join("\n",
        "Use this screen to review or enter the values requested by the current step.",
        "",
        "General tips:",
        "- Fill in the fields from top to bottom.",
        "- Watch the formula banner to see how the result is calculated.",
        "- Resolve warnings before moving forward when possible.",
        "- Use Save Draft if you want to continue the project later."
    );

    private static final Map<String, String> GUIDES = Map.ofEntries(
        Map.entry("Main Menu", String.join("\n",
            "Purpose:",
            "This is the main menu where you create, open, import, export, rename, and delete solar sizing projects.",
            "",
            "Main areas:",
            "- Total Projects shows how many saved project files are currently available.",
            "- Save Location shows where SolarWizard stores project files.",
            "- Past Computed Projects lists saved projects that you can reopen.",
            "",
            "Common actions:",
            "- Start Drafting Now creates a new solar sizing project.",
            "- Open loads an existing project.",
            "- Import brings in a .swproj file from another location.",
            "- Export saves a copy of a project file.",
            "- Change Directory moves the project storage location.",
            "",
            "Tip:",
            "If a project does not appear in the list, check that the Save Location points to the folder where the project file is stored."
        )),
        Map.entry("Appliances", String.join("\n",
            "Purpose:",
            "Estimate the daily load that the solar system must support.",
            "",
            "What to enter:",
            "- Device mode: add each appliance, its wattage, hours per day, quantity, and motor flag.",
            "- Direct mode: use monthly kWh from an electric bill.",
            "- Bill mode: use monthly bill amount and rate per kWh.",
            "",
            "Important fields:",
            "- Peak Hr estimates how long a device runs during the busiest usage period.",
            "- DF means demand factor. It estimates how much of the connected load is used at the same time.",
            "- Motor loads add surge allowance for appliances such as refrigerators, pumps, and air conditioners.",
            "",
            "Output:",
            "This step produces Daily Consumption, Peak Simultaneous Load, and a recommended inverter basis."
        )),
        Map.entry("Energy Requirement", String.join("\n",
            "Purpose:",
            "Convert daily consumption into the total energy the system should support.",
            "",
            "What to enter:",
            "- System Loss Buffer accounts for inverter losses, wiring losses, temperature, and real-world inefficiency.",
            "- Days of Autonomy is the number of days the system should run without useful solar charging.",
            "",
            "Suggested values:",
            "- 30% system loss buffer is a common planning reference.",
            "- At least 2 autonomy days is useful for rainy-season planning.",
            "",
            "Output:",
            "Total Energy Requirement is passed to battery sizing."
        )),
        Map.entry("Battery Bank", String.join("\n",
            "Purpose:",
            "Size the battery bank needed to store the required energy.",
            "",
            "What to enter:",
            "- Battery nominal voltage, such as 12V, 24V, 48V, or 51.2V.",
            "- Capacity in Ah for one battery.",
            "- Battery quantity in the bank.",
            "- Depth of Discharge (DOD), which is the usable fraction of the battery.",
            "",
            "Suggested values:",
            "- Lead-acid batteries often use around 50% DOD.",
            "- LiFePO4 batteries often use around 80% DOD.",
            "",
            "Output:",
            "Recommended Energy Consumption is passed to solar panel sizing."
        )),
        Map.entry("Panel Array", String.join("\n",
            "Purpose:",
            "Calculate how many solar panels are needed to recharge the battery energy target.",
            "",
            "What to enter:",
            "- Panel wattage, Voc, Vmp, Isc, and Imp from the panel datasheet.",
            "- Peak Sun Hours using a conservative local estimate.",
            "- Wiring configuration: parallel adds current, series adds voltage.",
            "",
            "Important checks:",
            "- Voc affects charge controller voltage safety.",
            "- Isc and Imp affect charge controller and wire sizing.",
            "",
            "Output:",
            "Panels Needed, Total PV Power, and array electrical values are used by the charge controller step."
        )),
        Map.entry("Charge Controller", String.join("\n",
            "Purpose:",
            "Check that the solar charge controller can safely handle the panel array and battery bank.",
            "",
            "What to enter:",
            "- Controller type: MPPT or PWM.",
            "- Rated charge current.",
            "- Max PV input voltage.",
            "- Max PV input power.",
            "",
            "Important checks:",
            "- Array Voc must be below the controller max PV input voltage.",
            "- Array watts should stay within the controller power rating.",
            "- MPPT is usually preferred for flexible panel wiring and higher array voltage.",
            "",
            "Output:",
            "Required SCC current and array limits are used by wire and breaker sizing."
        )),
        Map.entry("Inverter Sizing", String.join("\n",
            "Purpose:",
            "Choose an inverter rating that can support the expected simultaneous load.",
            "",
            "What to enter:",
            "- Inverter brand and model for documentation.",
            "- Rated Power from the inverter datasheet.",
            "",
            "Important checks:",
            "- The rated inverter power should be higher than the calculated minimum inverter watts.",
            "- Motor loads may need extra surge capacity beyond the continuous rating.",
            "",
            "Output:",
            "The inverter rating is used for battery-to-inverter wire sizing and breaker sizing."
        )),
        Map.entry("Wire Sizing", String.join("\n",
            "Purpose:",
            "Estimate wire sizes for the main PV, battery, inverter, and AC load runs.",
            "",
            "What to enter:",
            "- Distance for each wiring section.",
            "- DC voltage drop percentage. A conservative reference is 2% for DC sections.",
            "",
            "How to use the table:",
            "- Current and voltage come from earlier steps.",
            "- AWG is selected from the VDI calculation.",
            "- PEC breaker and copper size columns help cross-check practical conductor sizing.",
            "",
            "Tip:",
            "Keep battery-to-inverter wiring as short as possible because current is usually high."
        )),
        Map.entry("Circuit Breakers", String.join("\n",
            "Purpose:",
            "Estimate protection device ratings for each major circuit.",
            "",
            "How to read the table:",
            "- Panels to SCC uses adjusted Isc with safety factors.",
            "- SCC to Battery uses controller output current when available.",
            "- Battery to Inverter and Inverter to AC Load use inverter current with margin.",
            "",
            "Important checks:",
            "- Use DC-rated breakers for PV, charge controller, and battery circuits.",
            "- Use AC-rated breakers only on the inverter AC output side.",
            "- Final protection selection should follow local electrical code and installer judgment."
        )),
        Map.entry("Summary Report", String.join("\n",
            "Purpose:",
            "Review the complete system recommendation before saving, printing, or using it as project documentation.",
            "",
            "What to check:",
            "- Any warning banners at the top of the report.",
            "- Battery, panel, charge controller, and inverter ratings.",
            "- Wire and breaker recommendations for each circuit section.",
            "",
            "Tip:",
            "If a result looks wrong, use the sidebar to return to the related step and adjust the input."
        ))
    );

    private GuideService() {}

    public static String guideFor(String stepTitle) {
        return GUIDES.getOrDefault(stepTitle, FALLBACK_GUIDE);
    }
}
